import { GoalPlan } from '../models/goalPlan';

export async function ensureWeeklyGoal(studentId: string) {
  const existing = await GoalPlan.findOne({ studentId, seedKey: 'goal-weekly' });
  if (existing) return existing;
  return GoalPlan.create({
    studentId,
    seedKey: 'goal-weekly',
    moduleCode: 'WEEK',
    moduleName: 'Study plan',
    title: 'Weekly study goal',
    summary: 'Default weekly target. Hours count while UniMentor is open.',
    priority: 'Default',
    progress: 0,
    gradeLabel: '0h',
    targetPercent: 20,
    targetGrade: '20h',
    delta: '20h left',
    daysLeft: 7,
    dueLabel: 'This week',
    hoursLogged: 0,
    supportLabel: 'App open time',
    tutorName: 'Your study plan',
    tutorRole: 'Weekly goal',
    tutorSlot: 'While the app is open',
    credentialId: 'WEEKLY-20H',
    completed: false,
    topics: [],
    analytics: {
      projected: 0,
      projectedGrade: '20h',
      certainty: 0,
      baseline: 0,
      midterm: 0,
      selfStudy: 100,
      tutoring: 0,
      groups: 0,
      pace: 'Counted from app open time',
    },
    milestones: [
      { id: 'w1', title: 'Open UniMentor and study', detail: 'Time counts automatically', status: 'active', dueLabel: 'This week' },
    ],
    assessments: [],
    tasks: [
      { id: 'wt1', title: 'Review this week\'s module notes', kind: 'Revision', minutes: 45, dueLabel: 'This week', status: 'open' },
      { id: 'wt2', title: 'Practice problems for the active goal', kind: 'Problem Set', minutes: 60, dueLabel: 'This week', status: 'open' },
    ],
    tutors: [],
    sessions: [],
  });
}

export async function ensureGoalPlans(studentId: string): Promise<void> {
  await ensureWeeklyGoal(studentId);
  const existing = await GoalPlan.exists({ studentId, seedKey: 'goal-graph' });
  if (existing) return;

  await GoalPlan.insertMany([
    {
      studentId,
      seedKey: 'goal-graph',
      moduleCode: 'IT2040',
      moduleName: 'Data Structures & Algorithms',
      title: 'Master Graph Traversals & Tree Recursion',
      summary: 'Targeting mastery across advanced BFS/DFS, MSTs, and AVL trees.',
      priority: 'High Priority',
      progress: 72,
      gradeLabel: 'B+',
      targetPercent: 80,
      targetGrade: 'A-',
      delta: '+8%',
      daysLeft: 24,
      dueLabel: 'Due 18 Oct 2026',
      hoursLogged: 48.5,
      supportLabel: '1 Mentor • 1 POD',
      tutorName: 'Tharushi Perera',
      tutorRole: 'Lead Peer Tutor',
      tutorSlot: 'Thu 14:00',
      credentialId: 'KPP-2026-IT8821',
      completed: false,
      topics: [
        { title: 'Graph BFS & DFS', score: 93, note: 'Mastered' },
        { title: "Dijkstra's Algorithm", score: 86, note: 'Strong' },
        { title: 'Bellman-Ford & Cycles', score: 68, note: 'Needs Focus' },
      ],
      analytics: {
        projected: 88,
        projectedGrade: 'A',
        certainty: 94,
        baseline: 64,
        midterm: 78,
        selfStudy: 55,
        tutoring: 25,
        groups: 20,
        pace: '+8.0% Pace',
      },
      milestones: [
        { id: 'm1', title: 'Understand BFS vs DFS implementation', detail: 'Done', status: 'done', dueLabel: 'Done' },
        { id: 'm2', title: 'Solve 15 LeetCode Graph Problems', detail: 'Done', status: 'done', dueLabel: '02 Oct' },
        { id: 'm3', title: "Dijkstra & Shortest Path Sets", detail: '3/5 Solved', status: 'active', dueLabel: '3/5 Solved', progressLabel: '3/5 Solved' },
        { id: 'm4', title: 'AVL Tree Rotations & Balance Factor', detail: 'Next', status: 'locked', dueLabel: '12 Oct' },
        { id: 'm5', title: 'Comprehensive Mock Exam Simulation', detail: 'Final capstone', status: 'locked', dueLabel: '18 Oct' },
      ],
      assessments: [
        {
          id: 'a-mid',
          name: 'Mid-Semester Examination',
          type: 'Exam',
          dateLabel: '18 Oct 2026',
          timeLabel: '09:00',
          totalMarks: 100,
          targetMark: 85,
          weight: 25,
          score: 88,
          statusLabel: 'Graded',
          evidence: 'Graded_MidTerm_Paper_Scan.pdf',
          feedback: "Outstanding improvement on AVL rotations! For the final exam, let's reinforce Bellman-Ford negative edge proof.",
        },
        {
          id: 'a-code',
          name: 'Graph Algorithms Coding Suite',
          type: 'Assignment',
          dateLabel: '12 Oct 2026',
          timeLabel: '23:59',
          totalMarks: 100,
          targetMark: 80,
          weight: 15,
          score: 78,
          statusLabel: 'Achieved',
          evidence: 'coding-suite.zip',
          feedback: 'Solid implementations. Tighten the Dijkstra decrease-key notes.',
        },
        {
          id: 'a-quiz',
          name: 'Tree Traversal Speed Quiz',
          type: 'Quiz',
          dateLabel: '12 Oct 2026',
          timeLabel: '16:00',
          totalMarks: 100,
          targetMark: 85,
          weight: 10,
          score: 90,
          statusLabel: 'Due 12 Oct',
          evidence: 'quiz-attempt.pdf',
          feedback: 'Fast and accurate on rotations.',
        },
      ],
      tasks: [
        { id: 't1', title: 'Bellman-Ford Relaxation Proof & LeetCode #743', kind: 'Problem Set', minutes: 45, dueLabel: 'Due Today 6:00 PM', status: 'open' },
        { id: 't2', title: 'Review Lecturer Feedback on Mid-Term Paper PDF', kind: 'Revision', minutes: 20, dueLabel: 'Pending', status: 'open' },
      ],
      tutors: [
        { key: 'tharushi', name: 'Tharushi Perera', rating: 4.9, price: 'LKR 2,000/hr', specialty: 'Bellman-Ford Specialist', slot: 'Today, 4:30 PM (Online Pod)', verified: true },
        { key: 'kasun', name: 'Kasun J.', rating: 4.8, price: 'LKR 1,800/hr', specialty: 'DAGs & Shortest Paths', slot: 'Tomorrow, 6:00 PM', verified: false },
        { key: 'dinithi', name: 'Dinithi Alwis', rating: 4.7, price: 'LKR 1,500/hr', specialty: 'Recursion & Trees', slot: 'Sat, 10:00 AM', verified: false },
      ],
      sessions: [
        { id: 's1', title: 'DSA Squad Study Group', when: 'Wed 11 Oct • 6:30 PM' },
        { id: 's2', title: '1-on-1 Kuppiya with Tharushi', when: 'Fri 13 Oct • 2:00 PM' },
      ],
    },
    {
      studentId,
      seedKey: 'goal-oop',
      moduleCode: 'SE3010',
      moduleName: 'Software Architecture',
      title: 'OOP Polymorphism Quiz',
      summary: 'Separate abstract classes from interfaces before the midterm.',
      priority: 'Medium',
      progress: 40,
      gradeLabel: 'C+',
      targetPercent: 75,
      targetGrade: 'B',
      delta: '+6%',
      daysLeft: 12,
      dueLabel: 'Midterm Prep',
      hoursLogged: 6,
      supportLabel: '1 Mentor',
      tutorName: 'Tharushi Perera',
      tutorRole: 'Peer Tutor',
      tutorSlot: 'Fri 14:00',
      credentialId: 'KPP-2026-SE3010',
      completed: false,
      topics: [
        { title: 'Polymorphism', score: 70, note: 'Growing' },
        { title: 'Abstract classes', score: 62, note: 'Needs Focus' },
        { title: 'Interfaces', score: 74, note: 'Strong' },
      ],
      analytics: {
        projected: 76,
        projectedGrade: 'B',
        certainty: 80,
        baseline: 58,
        midterm: 66,
        selfStudy: 70,
        tutoring: 20,
        groups: 10,
        pace: '+6.0% Pace',
      },
      milestones: [
        { id: 'o1', title: 'List polymorphism examples from lectures', detail: 'Done', status: 'done', dueLabel: 'Done' },
        { id: 'o2', title: 'Contrast abstract class vs interface', detail: 'In progress', status: 'active', dueLabel: '2/4 notes', progressLabel: '2/4 notes' },
        { id: 'o3', title: 'Timed concept quiz', detail: 'Next', status: 'locked', dueLabel: 'Next' },
      ],
      assessments: [],
      tasks: [
        { id: 'ot1', title: 'Rewrite the shape hierarchy without shared fields', kind: 'Revision', minutes: 30, dueLabel: 'Due Tomorrow', status: 'open' },
      ],
      tutors: [
        { key: 'tharushi', name: 'Tharushi Perera', rating: 4.9, price: 'LKR 2,000/hr', specialty: 'OOP and architecture', slot: 'Fri, 2:00 PM', verified: true },
      ],
      sessions: [
        { id: 'os1', title: 'Architecture clinic', when: 'Thu 16 Oct • 4:00 PM' },
      ],
    },
  ]);
}
